version: '3'
services:
  nginx:
    container_name: nginx
    image: nginx:latest
    restart: always
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./conf/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./conf/nginx/conf.d:/etc/nginx/conf.d
      - ./site-data:/home/site-data
      - certbot_data:/var/www/certbot
      - certbot_config:/etc/letsencrypt
    networks:
      - nginx_net
  
  certbot:
    container_name: certbot
    image: certbot/certbot:arm64v8-latest
    volumes:
      - certbot_data:/var/www/certbot
      - certbot_config:/etc/letsencrypt
      - certbot_libs:/var/lib/letsencrypt
    networks:
      - nginx_net
  
  nginx-exporter:
    container_name: nginx-exporter
    image: nginx/nginx-prometheus-exporter:latest
    ports:
      - 9100:9113
    command:
      - -nginx.scrape-uri
      - http://nginx/status
    networks:
      - nginx_net

volumes:
  certbot_data:
  certbot_config:
  certbot_libs:

networks:
  nginx_net: