services:
  nginx:
    container_name: nginx
    image: nginx:latest
    restart: always
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./conf/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./conf/nginx/conf.d:/etc/nginx/conf.d
      - ./site-data:/home/site-data
      - certbot_data:/var/www/certbot
      - certbot_config:/etc/letsencrypt
  
  certbot:
    container_name: certbot
    image: certbot/certbot:arm64v8-latest
    volumes:
      - certbot_data:/var/www/certbot
      - certbot_config:/etc/letsencrypt
      - certbot_libs:/var/lib/letsencrypt

volumes:
  certbot_data:
  certbot_config:
  certbot_libs: